### ISSUE TITLE
Text change background-color 

### ISSUE THREAD

**Issue by teamhide** [SeregPie/THREE.TextSprite#10]
I'm using your library very well.

But, is there any argument that can remove(or change) background-color?

Default color is black, but I have to change it.

Thanks.

**Comment by teamhide** [comment]
I found bug.

When I add `axesHelper`, background-color was removed.

```
var axesHelper = new THREE.AxesHelper( 5 );
scene.add( axesHelper );
```

But, I want a clear solution.

**Comment by SeregPie** [comment]
The black background is removed automatically if the material is transparent.

https://seregpie.github.io/THREE.TextTexture/
