### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by thedrint** [SeregPie/THREE.TextSprite#12]
Hi.
I've try to write simple scene. My workaround is Windows 10, Chrome 69.

Installed your package from npm.

Imported it to my project with `import TextSprite from 'three.textsprite';`

My camera settings:
```
camera = new THREE.PerspectiveCamera(75, window.innerWidth/window.innerHeight, 1/128, 1000);
```

Try to add some text to scene:
```
let sprite = new TextSprite({
	textSize: 0.1,
	texture: {
		text: sometext,
		fontFamily: 'Arial, Helvetica, sans-serif',
	},
	material: {color: 'white'},
});
sprite.position.set(0,5,-10);
scene.add( sprite );
```

![2018-09-23_01-35-47](https://user-images.githubusercontent.com/5421805/45922312-12f09880-bed1-11e8-96df-dd658cc31f43.png)

Text is some white glowing in front of camera.

But if i move camera closer to text position, this result:

![2018-09-23_01-37-25](https://user-images.githubusercontent.com/5421805/45922328-0f114600-bed2-11e8-82b8-1eb4324a216c.png)

If it important, camera binded to player object.

In your demo (on my machine) text always renders with good contrast and shapes. In my example, it looks like 8bit text and become normally visible only if camera near text postion:(

Where i was wrong in my code? What can i do to improve text rendering?

**Comment by SeregPie** [comment]
Hi.

It would help, if you could upload this snippet to a codepen or similar.

Have you tested it with other text size and font family?

Try a short text, like 3 letters. Maybe we can limit the cause this way.

**Comment by thedrint** [comment]
Thank you for reply, @SeregPie 
I don't think I can do codepen from my code - it bundled with webpack.

I can take you link for  [addText function declaration](https://github.com/igorbarkowsky/warband2d/blob/master/src/game/engines/ThreeEngine.js#L328)
And link to [addText function call in my setupScene method](https://github.com/igorbarkowsky/warband2d/blob/master/src/game/engines/ThreeEngine.js#L201)

This is [playable demo](https://igorbarkowsky.github.io/warband2d/), source-map included.
Helper text appers at world coords (0, 1, -3). Click for start capturing mouse and keyboards, WASD for move, mouse for rotate.

I found that there is direct relationship between camera position and text position. Text become unreadable at long and middle distances (>2-3 Three.js meters).

**Comment by m0ose** [comment]
I believe a very small font is being chosen by https://github.com/SeregPie/THREE.TextSprite/blob/master/src/index.js#L57 . I had the same problem with one particular scene, and not others.

**Comment by SeregPie** [comment]
@igorbarkowsky 
another idea. overwrite my class with some console output.

```js
let DummySprite = class extends TextSprite {
  onBeforeRender(...args) {
    console.log('onBeforeRender called!');
    return super.onBeforeRender(...args);
  }
};
```

i would like to know if `onBeforeRender` is called.
