### ISSUE TITLE
error on show but work

### ISSUE THREAD

**Issue by anakein** [SeregPie/THREE.TextSprite#14]
i have working your script, but when show in the console i have this error:
 TypeError: s.Math.ceilPowerOfTwo is not a function     three.textsprite:1:1625

**Comment by SeregPie** [comment]
hello. looks like you have a [very old three.js version](https://github.com/mrdoob/three.js/releases/tag/r88).
i use this [function](https://threejs.org/docs/index.html#api/en/math/Math.ceilPowerOfTwo).
