### ISSUE TITLE
WebVR - TextSprite only renders in one eye

### ISSUE THREAD

**Issue by welshtom** [SeregPie/THREE.TextSprite#2]
When using the TextSprite to create a rudimentary "HUD" it only renders in the right eye view of the WEBVR view.

**Comment by SeregPie** [comment]
Hmm... I have no expirience with multiple cameras.
I will look into this, when I will have time.

**Comment by SeregPie** [comment]
This isn't the problem of `TestSprite`. It's the problem of `Sprite` in general.
https://github.com/mrdoob/three.js/issues/11726
