### ISSUE TITLE
Can't import ES Module

### ISSUE THREAD

**Issue by aurelien-bcn** [SeregPie/THREE.TextSprite#20]
Hi,

I installed your package with npm and I can't import the module by this way : 

```
<script type="module">
    import * as THREE from '../node_modules/three/build/three.module.js';
    // import ThreeSprite from '../node_modules/@seregpie/three.text-sprite/index.js';
    import { ThreeSprite } from '../node_modules/@seregpie/three.text-sprite/index.js';
</script>
```

I get this error in console : 
without `{}`
```
Uncaught SyntaxError: The requested module '../node_modules/@seregpie/three.text-sprite/index.js'
does not provide an export named 'ThreeSprite'
```

with `{}`
```
Uncaught SyntaxError: The requested module '../node_modules/@seregpie/three.text-sprite/index.js'
does not provide an export named 'default'
```

**Comment by BingXiong1995** [comment]
@aurelien-bcn I met this problem too, have you solved it?

**Comment by SeregPie** [comment]
Yes. It's not possible to import an umd like this.

https://github.com/umdjs/umd/issues/124
https://github.com/umdjs/umd/issues/134

It needs another build.

For now I don't have any time to make a support for it. Webpack is still the primary way to go.
=(
