### ISSUE TITLE
Disappears when used with AnaglyphEffect

### ISSUE THREAD

**Issue by jason-edward-young** [SeregPie/THREE.TextSprite#21]
Hi, this library works really well, but when I use it with the AnaglyphEffect the text disappears.

**Comment by jason-edward-young** [comment]
Actually, the text is present, it's just very large and at a weird position. It's 3D coordinates don't seem to be in sync with other objects in the scene. And, when I change the camera's perspective (with orbit controls) the text doesn't respond.

**Comment by SeregPie** [comment]
Sorry. I don't know how to help here.
