### ISSUE TITLE
Change part of array to bold?

### ISSUE THREAD

**Issue by gitnoob23** [SeregPie/THREE.TextSprite#26]
Hello,

Awesome project! Was just wondering if it was possible if I could make part of my array of text bold?

I was having issues with alignment, and have a good amount of text that I am working with. But basically I have a block of text where the first line of the block is the title, which ideally would be larger and bold.

I had them as two text sprites, but was struggling to make them left align together, since they are two different lengths, I couldn't figure out how to anchor them so they appear to be part of the same paragraph, so figured it would be easier to put all of my text in one array, but now I am unsure if I can make the first part of it bold.

Thanks!

**Comment by SeregPie** [comment]
Hi.
This change would need to support some sort of a markdown. This would make the library much more complex. I don't think I will ever have time for this if it is not needed for my work.
=(

**Comment by jtomek** [comment]
That's exactly what we're planning to implement for our own use case. We'll base is on the Delta object (Quill) as a standard for storing text and size & render substrings. The biggest fear right now is how to do overflows. Anyway, if there is something easy and shareable once we're done, I'll be happy to share it with you.
