### ISSUE TITLE
How to add multiline text?

### ISSUE THREAD

**Issue by mariokam** [SeregPie/THREE.TextSprite#3]
I am playing with it and not sure, how to add multiline longer texts?
Any ideas?

**Comment by SeregPie** [comment]
There are no automatically line breaks.
You can add lines with `\n`.

```js
sprite.material.map.text = [
  'line one',
  'line two',
  'line three',
].join('\n');
```

Look [here](https://seregpie.github.io/THREE.TextTexture/).
