### ISSUE TITLE
Is background color possible?

### ISSUE THREAD

**Issue by vectris-dev** [SeregPie/THREE.TextSprite#5]
I've been attempting to change the background using a spritemap, however it's ignored in

```
var spriteMap = new THREE.TextureLoader().load('textures/white.png');
var spriteMaterial = new THREE.SpriteMaterial({
	map: spriteMap,
	color: 0xffffff
});
var mat = new THREE.Sprite(spriteMaterial);
for (j = 0; j < 100; j++) {
	let sprite = new THREE.TextSprite({
		textSize: 1,
		redrawInterval: 250,
		texture: {
			text: wrapText(titles[j], 30),
			fontFamily: 'Arial, Helvetica, sans-serif',
		},
		mat
	});
```
            

I assume I'm doing this entirely wrong, is it possible to add background colors in some way?

**Comment by SeregPie** [comment]
Try to set material to not transparent.

**Comment by Sevrex** [comment]
The object returns transparent:false when I console log it and it's opacity is also set to 1. I've edited the above code to use your example so that it's more readable, I'm sure I'm missing something simple.

**Comment by SeregPie** [comment]
You are using it wrong. Look inside readme.
https://github.com/SeregPie/THREE.TextSprite#members
