### ISSUE TITLE
param textSize and fontSize(px)  relation

### ISSUE THREAD

**Issue by Davidyanlong** [SeregPie/THREE.TextSprite#6]
your demo is really clear!  How to convert textSize into fontsize?

**Comment by Davidyanlong** [comment]
I hope set textSize value ,renderer text size is actual size

**Comment by SeregPie** [comment]
`fontSize` is set automatically. Just set `textSize`. `textSize` is the size that THREE uses for its 3D objects.

```javascript
let sprite = new THREE.TextSprite({
  textSize: 10,
  texture: {text: 'Carpe Diem'},
  material: {color: 0xffbbff},
});
scene.add(sprite);
```

**Comment by Davidyanlong** [comment]
I done!
you look my demo [demo](https://codepen.io/davidyanlong/pen/VBGqxg)

**Comment by Davidyanlong** [comment]
Thank you very much for your patient answer

**Comment by Davidyanlong** [comment]
I need the size of the text to be fixed in three-dimensional space, and the size of the text is set according to the pixel value (px), regardless of the camera's distance.

**Comment by Davidyanlong** [comment]
On your basis, I made changes, and the final result was [https://codepen.io/davidyanlong/pen/YjJdgB](https://codepen.io/davidyanlong/pen/YjJdgB)

**Comment by Davidyanlong** [comment]
I don't quite understand this code. Why do I make this text clear?

```
let distance = object.getWorldPosition(objectWorldPosition).distanceTo(camera.getWorldPosition(cameraWorldPosition));
		if (distance) {
			let heightInPixels = object.getWorldScale(objectWorldScale).y * renderer.domElement.height / distance;
			if (heightInPixels) {
				return Math.round(heightInPixels / object.material.map.imageHeight);
			}
		}
```

**Comment by SeregPie** [comment]
I think I have an idea. I will try something today.

**Comment by SeregPie** [comment]
This should be it.
https://codepen.io/SeregPie/pen/QBJrvX
