### ISSUE TITLE
Cannot resize sprite when using Reactjs

### ISSUE THREAD

**Issue by SneakySoySauce** [SeregPie/THREE.TextSprite#7]
Hello, your module does exactly what I need..
The only issue is that I'm trying to make it work with reactjs.

I use `const TextSprite = require('three.textsprite');` in order to use it.

When I zoom in or out, the sprite keeps its size and sometimes gets blurry while the cube on the same scene changes size.

Is there a way to manually trigger the sprite update ?

Thanks.

**Comment by SeregPie** [comment]
Hello.

You can trigger update manually with the function `.redrawNow(renderer, camera)`.
You can also set `redrawInterval` to `0`.

**Comment by SneakySoySauce** [comment]
Thank you for the fast answer, sadly it didn't work.

Here is an example of a sprite after I zoom out : 
![image](https://user-images.githubusercontent.com/33459843/45036864-c65f2d80-b087-11e8-86fb-e8d41b6f63ad.png)

Any idea of what could cause this behaviour ?

**Comment by SeregPie** [comment]
Can you upload it to a jsfiddle?

**Comment by SneakySoySauce** [comment]
Unfortunately I couldn't manage to get one working, I created a Sprite/canvas in order to compare and the scaling updates automatically so I don't know what's wrong.
Anyway you can keep it the issue closed, I was just trying to play with the library , thanks.

**Comment by SeregPie** [comment]
The only thing I can think of, is that the THREE version in your project is outdated. If you have an older version, then `onBeforeRender` is never called.

**Comment by SneakySoySauce** [comment]
I'm using r96, currently the most recent.
